apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consumer-notification-job
spec:
  destination:
    namespace: local-consumer-staging
    server: https://kubernetes.default.svc
  project: consumer
  source:
    helm:
      valueFiles:
      - ../valuesStg.yaml
    path: helmCharts/consumer_notification-job
    repoURL: https://nguyengt@bitbucket.org/nguyengt/argo-test.git
    targetRevision: HEAD
